# Generated by Django 5.2.6 on 2025-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('sepatu', 'Sepatu'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('aksesoris', 'Aksesoris')], default='sepatu', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
    ]
