# Generated by Django 5.2.6 on 2025-09-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu', 'Sepatu'), ('bola', 'Bola'), ('jersey', 'Jersey'), ('aksesoris', 'Aksesoris')], max_length=255),
        ),
    ]
